/*
 * generated by Xtext 2.10.0
 */
package de.htwdd.sf.beleg.s72868.s73331


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ReneMartinRuntimeModule extends AbstractReneMartinRuntimeModule {
}
