/*
 * generated by Xtext 2.10.0
 */
package de.htwdd.sf.beleg.s72868.s73331


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ReneMartinStandaloneSetup extends ReneMartinStandaloneSetupGenerated {

	def static void doSetup() {
		new ReneMartinStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
