/*
 * generated by Xtext 2.10.0
 */
package de.htwdd.sf.beleg.s72868.s73331.tests

import com.google.inject.Inject
import de.htwdd.sf.beleg.s72868.s73331.reneMartin.Model
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(ReneMartinInjectorProvider)
class ReneMartinParsingTest{

	@Inject
	ParseHelper<Model> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
