/*
 * generated by Xtext 2.10.0
 */
package de.htwdd.sf.beleg.s72868.s73331.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class ReneMartinUiModule extends AbstractReneMartinUiModule {
}
